# Generated by Django 5.2.17 on 2026-09-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDayAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_loss_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_loss_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_recovery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.plantday')),
                ('recommend_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.crew')),
            ],
        ),
    ]
