# Generated by Django 5.2.17 on 2026-09-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0002_remove_crewassignment_unique_crew_plant_date_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDayAiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.plantday')),
            ],
        ),
    ]
