# Generated by Django 6.1.1 on 2026-09-18 06:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('capacity_mw', models.DecimalField(decimal_places=10, max_digits=15)),
                ('tariff_per_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_base', models.CharField(max_length=100)),
                ('mw_per_day', models.DecimalField(decimal_places=10, max_digits=15)),
                ('day_rate_usd', models.DecimalField(decimal_places=10, max_digits=15)),
                ('serviceable_plants', models.ManyToManyField(related_name='crews', to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('plants', models.ManyToManyField(related_name='owners', to='core.plant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PlantDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_kwh', models.DecimalField(decimal_places=10, max_digits=20)),
                ('expected_energy_kwh', models.DecimalField(decimal_places=10, max_digits=20)),
                ('performance_ratio', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('soiling_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_until_next_reset', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cleaned', models.BooleanField()),
                ('plant_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.plantday')),
            ],
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('estimate_days', models.IntegerField()),
                ('estimate_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crew')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('crew_id', 'plant_id', 'date'), name='unique_crew_plant_date_relation')],
            },
        ),
        migrations.AddConstraint(
            model_name='plantday',
            constraint=models.UniqueConstraint(fields=('plant_id', 'date'), name='unique_plant_date_relation'),
        ),
    ]
