# Generated by Django 5.2.17 on 2026-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crewassignment',
            name='unique_crew_plant_date_relation',
        ),
        migrations.AddConstraint(
            model_name='crewassignment',
            constraint=models.UniqueConstraint(fields=('crew', 'plant', 'date'), name='unique_crew_plant_date_relation'),
        ),
    ]
